const PDFDocument = require('pdfkit-table');

const {
  calculateDashboard,
  attendanceInsights,
  attritionAnalysis,
  payrollInsights,
  recruitmentInsights
} = require('./hrLogic');

const { listLeaves } = require('./hrStore');
const { generateDailySummary } = require('./aiService');

async function generateHrSummaryPdf(res) {
  const [
    dashboard,
    attendance,
    attrition,
    payroll,
    recruitment,
    leaves,
    summary
  ] = await Promise.all([
    calculateDashboard(),
    attendanceInsights(),
    attritionAnalysis(),
    payrollInsights(),
    recruitmentInsights(),
    listLeaves(),
    generateDailySummary()
  ]);

  const doc = new PDFDocument({
    margin: 40,
    size: 'A4',
    bufferPages: true
  });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    'attachment; filename="hr-summary.pdf"'
  );

  doc.pipe(res);

  // ==========================
  // HEADER
  // ==========================

  doc
    .fontSize(24)
    .fillColor('#0f172a')
    .text('Company HR Report', {
      align: 'center'
    });

  doc
    .fontSize(10)
    .fillColor('#64748b')
    .text(
      `Generated On: ${new Date().toLocaleString()}`,
      {
        align: 'center'
      }
    );

  doc.moveDown(2);

  // ==========================
  // REPORT INFO
  // ==========================

  await doc.table({
    title: 'Report Information',
    headers: ['Field', 'Value'],
    rows: [
      ['Database', 'PostgreSQL'],
      ['Report Type', 'HR Executive Report'],
      ['Generated By', 'AI Analytics Engine'],
      ['Source', 'Live Workforce Data']
    ]
  });

  doc.moveDown();

  // ==========================
  // KPI TABLE
  // ==========================

  await doc.table({
    title: 'Workforce Overview',
    headers: ['Metric', 'Value'],
    rows: [
      ['Total Employees', dashboard.totalEmployees],
      ['Attendance Rate', `${dashboard.attendanceRate}%`],
      ['High Attrition Risk', dashboard.attritionRiskCount],
      ['Open Leave Requests', dashboard.openLeaveRequests],
      ['Recruitment Pipeline', dashboard.hiringPipeline]
    ]
  });

  doc.moveDown();

  // ==========================
  // ATTENDANCE
  // ==========================

  await doc.table({
    title: 'Attendance Summary',
    headers: ['Present', 'Late', 'Absent'],
    rows: [
      [
        attendance.summary.presentCount,
        attendance.summary.lateCount,
        attendance.summary.absentCount
      ]
    ]
  });

  doc.moveDown();

  // ==========================
  // ATTRITION
  // ==========================

  await doc.table({
    title: 'High Risk Employees',
    headers: ['Employee', 'Risk', 'Score'],
    rows: attrition.slice(0, 10).map((emp) => [
      emp.name,
      emp.risk,
      emp.riskScore
    ])
  });

  doc.moveDown();

  // ==========================
  // PAYROLL
  // ==========================

  await doc.table({
    title: 'Payroll Analytics',
    headers: [
      'Employee',
      'Net Salary',
      'Benchmark'
    ],
    rows: payroll.map((item) => [
      item.employeeId,
      item.net,
      item.benchmarkLabel
    ])
  });

  doc.moveDown();

  // ==========================
  // RECRUITMENT
  // ==========================

  await doc.table({
    title: 'Recruitment Pipeline',
    headers: [
      'Open Jobs',
      'Applications'
    ],
    rows: [
      [
        recruitment.jobs.length,
        recruitment.applications.length
      ]
    ]
  });

  doc.moveDown();

  // ==========================
  // LEAVE REQUESTS
  // ==========================

  await doc.table({
    title: 'Leave Requests',
    headers: [
      'Employee',
      'Type',
      'From',
      'To',
      'Status'
    ],
    rows: leaves.slice(0, 20).map((leave) => [
      leave.employeeId,
      leave.type,
      leave.from,
      leave.to,
      leave.status
    ])
  });

  doc.moveDown();

  // ==========================
  // AI EXECUTIVE SUMMARY
  // ==========================

  const summaryY = doc.y;

  doc
    .roundedRect(
      40,
      summaryY,
      510,
      140
    )
    .fillAndStroke(
      '#F8FAFC',
      '#CBD5E1'
    );

  doc
    .fillColor('#0F172A')
    .fontSize(16)
    .text(
      'AI Executive Summary',
      55,
      summaryY + 10
    );

  doc
    .fontSize(10)
    .fillColor('#334155')
    .text(
      summary.summary || 'No summary available.',
      55,
      summaryY + 35,
      {
        width: 470,
        align: 'justify'
      }
    );

  let bulletY = summaryY + 85;

  summary.bullets?.slice(0, 4).forEach((bullet) => {
    doc.text(
      `• ${bullet}`,
      65,
      bulletY,
      {
        width: 450
      }
    );

    bulletY += 18;
  });

  doc.moveDown(10);

  // ==========================
  // RECOMMENDATIONS
  // ==========================

  await doc.table({
    title: 'Recommended Actions',
    headers: [
      'Priority',
      'Recommendation'
    ],
    rows: [
      [
        'High',
        `Monitor ${dashboard.attritionRiskCount} employees showing elevated attrition risk`
      ],
      [
        'Medium',
        `${dashboard.openLeaveRequests} leave requests require approval review`
      ],
      [
        'Medium',
        'Investigate attendance anomalies and late arrivals'
      ],
      [
        'Low',
        'Improve recruitment funnel conversion rate'
      ]
    ]
  });

  // ==========================
  // FOOTER
  // ==========================

  const range = doc.bufferedPageRange();

  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);

    doc
      .fontSize(8)
      .fillColor('#64748b')
      .text(
        'Generated by Gemini AI',
        40,
        doc.page.height - 30
      );

    doc.text(
      'Database: PostgreSQL',
      180,
      doc.page.height - 30
    );

    doc.text(
      'Analytics Source: Live Workforce Data',
      320,
      doc.page.height - 30
    );

    doc.text(
      `Page ${i + 1} of ${range.count}`,
      0,
      doc.page.height - 30,
      {
        align: 'right'
      }
    );
  }

  doc.end();
}

module.exports = {
  generateHrSummaryPdf
};